security:
    ignore-cvss-severity-below: 4
    ignore-cvss-unknown-severity: False
    ignore-vulnerabilities:
      51668:
            # PVE-2022-51668, sqlalchemy str(engine.URL()) can leak password.
            reason: >-
              Our own code does not currently trigger any leaks.
              We *should* fix the issue, but there is no stable release of
              sqlalchemy 2 at time of writing.
              See RHELDST-15252. 
            expires: '2023-03-01'
      65213:
            # CVE-2023-6129, pyopenssl>=22.0.0,
            # POLY1305 MAC issue on PowerPC CPUs
            reason: >-
              Vulnerability is specific to PPC architecture, which is not
              used or relevant for this service.
            expires: '2025-04-04'
    continue-on-vulnerability-error: False
