name: Continuous Integration

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install tox

    - name: Build docker image
      run: |
        docker --version
        docker build . -f openshift/containers/exodus-gw/Dockerfile

    - name: Run auto-tests
      run: tox -e cov

    - name: Publish coverage
      uses: AndreMiras/coveralls-python-action@develop
      with:
        github-token: ${{ github.token }}

    - name: Run static analysis
      run: tox -e static

    - name: Build documentation
      run: tox -e docs

    - name: Publish documentation
      if: ${{ success() }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: scripts/push-docs
